# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0013_auto_20160407_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalystGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.SmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='GroupLivePrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('analyst_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.AnalystGroup')),
            ],
        ),
        migrations.CreateModel(
            name='LivePriceplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.SmallIntegerField()),
                ('cost', models.SmallIntegerField()),
                ('period_name', models.CharField(max_length=16, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='livepriceplan',
            unique_together=set([('days', 'cost')]),
        ),
        migrations.AddField(
            model_name='groupliveprices',
            name='live_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst.LivePriceplan'),
        ),
        migrations.AddField(
            model_name='analystgroup',
            name='liveprices',
            field=models.ManyToManyField(through='analyst.GroupLivePrices', to='analyst.LivePriceplan'),
        ),
        migrations.AlterUniqueTogether(
            name='groupliveprices',
            unique_together=set([('analyst_group', 'live_price')]),
        ),
    ]
