# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0014_auto_20160425_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyst',
            name='analyst_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analyst.AnalystGroup'),
        ),
    ]
