# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0004_auto_20160328_1100'),
        ('jcs', '0010_auto_20160426_1316'),
        ('analyst', '0015_analyst_analyst_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyst',
            name='banned_lettors',
            field=models.ManyToManyField(through='jcs.BannedLettor', to='mobileapp.AppUser'),
        ),
        migrations.AlterField(
            model_name='analyst',
            name='followers',
            field=models.ManyToManyField(related_name='followers', through='mobileapp.Follow', to='mobileapp.AppUser'),
        ),
    ]
