# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0016_auto_20160426_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyst',
            name='ban_chargeable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analyst',
            name='ban_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analyst',
            name='ban_letter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analyst',
            name='banchargeable_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='analyst',
            name='banfree_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='analyst',
            name='banletter_time',
            field=models.DateTimeField(null=True),
        ),
    ]
