# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_article_is_toppage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedWord',
            fields=[
                ('word', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
