# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0005_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='target_link',
            new_name='target_type',
        ),
        migrations.AddField(
            model_name='banner',
            name='target_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
