# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0008_auto_20160601_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigVIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('avatar', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='livevedio',
            name='guests',
        ),
        migrations.AddField(
            model_name='livevedio',
            name='guests',
            field=models.ManyToManyField(to='mobileapp.BigVIP'),
        ),
    ]
