# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0009_auto_20160605_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveGift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
                ('price', models.IntegerField()),
                ('useable', models.BooleanField()),
            ],
        ),
    ]
