# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0006_auto_20151223_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cup_name', models.CharField(max_length=16)),
                ('original_name', models.CharField(max_length=16)),
                ('stand_name', models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='teamname',
            unique_together=set([('cup_name', 'original_name')]),
        ),
    ]
