# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0007_auto_20160426_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamname',
            old_name='stand_name',
            new_name='standard_name',
        ),
    ]
