# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0008_auto_20160427_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.SmallIntegerField()),
                ('name', models.CharField(max_length=16)),
                ('logo', models.CharField(max_length=120, null=True)),
                ('introduction', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('sport_type', 'name')]),
        ),
    ]
