# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0010_match_lotterytypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
