# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0011_auto_20160505_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamname',
            name='checked',
            field=models.BooleanField(default=True),
        ),
    ]
