# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0012_teamname_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamname',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
