# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0015_prize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cup_name', models.CharField(max_length=16)),
                ('start_time', models.DateTimeField()),
                ('home_team', models.CharField(max_length=16)),
                ('away_team', models.CharField(max_length=16)),
                ('remark', models.CharField(max_length=100)),
            ],
        ),
    ]
