# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0016_fixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lottery.Match'),
        ),
    ]
