# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0017_fixture_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(db_index=True, max_length=16),
        ),
    ]
