# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 03:31
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jcs', '0010_auto_20160426_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlog',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='object_name',
        ),
        migrations.AddField(
            model_name='actionlog',
            name='action',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actionlog',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 19, 3, 31, 20, 905231, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actionlog',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actionlog',
            name='target',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
