# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcs', '0011_auto_20160519_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionlog',
            old_name='target',
            new_name='target_model',
        ),
        migrations.AddField(
            model_name='actionlog',
            name='memo',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='target_id',
            field=models.IntegerField(default=0),
        ),
    ]
